//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klijent
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int AerodromId { get; set; }
        public int PosedujeKompanijaId { get; set; }
        public int PosedujeAvionId { get; set; }
        public int LetId { get; set; }
    
        public virtual Aerodrom Aerodrom { get; set; }
        public virtual Poseduje Poseduje { get; set; }
        public virtual Let Let { get; set; }
    }
}
