//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Let
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Let()
        {
            this.Izvrsavas = new HashSet<Izvrsava>();
            this.Klijents = new HashSet<Klijent>();
        }
    
        public int Id { get; set; }
        public string Datum { get; set; }
        public string Vreme { get; set; }
        public string Destinacija { get; set; }
        public string MestoPolaska { get; set; }
        public int CentralaId { get; set; }
    
        public virtual Centrala Centrala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izvrsava> Izvrsavas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klijent> Klijents { get; set; }
    }
}
