//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aerodrom> Aerodromi { get; set; }
        public virtual DbSet<Avion> Avioni { get; set; }
        public virtual DbSet<Centrala> Centrale { get; set; }
        public virtual DbSet<Klijent> Klijenti { get; set; }
        public virtual DbSet<Osoblje> Osobljes { get; set; }
        public virtual DbSet<Upravlja> Upravljas { get; set; }
        public virtual DbSet<Let> Letovi { get; set; }
        public virtual DbSet<Izvrsava> Izvrsavas { get; set; }
        public virtual DbSet<Kompanija> Kompanije { get; set; }
        public virtual DbSet<Poseduje> Posedujes { get; set; }
    }
}
