//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upravlja
    {
        public int Id { get; set; }
        public int PilotId { get; set; }
        public int AvionId { get; set; }
    
        public virtual Pilot Pilot { get; set; }
        public virtual Avion Avion { get; set; }
    }
}
